---
controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100

    ur_joint_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    # 关节状态广播器
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      # state: active
      use_local_topics: false

ur_joint_velocity_controller:
  ros__parameters:
    # state: active
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity
      # gains:
      #   shoulder_pan_joint: {p: 50.0, i: 0.5, d: 5.0}
      #   shoulder_lift_joint: {p: 50.0, i: 0.5, d: 5.0}
      #   elbow_joint: {p: 40.0, i: 0.3, d: 4.0}
      #   wrist_1_joint: {p: 30.0, i: 0.2, d: 3.0}
      #   wrist_2_joint: {p: 30.0, i: 0.2, d: 3.0}
      #   wrist_3_joint: {p: 20.0, i: 0.1, d: 2.0}
