# Request part
float64 x  # 机器人操作器端点的x坐标
float64 y  # 机器人操作器端点的y坐标
float64 z  # 机器人操作器端点的z坐标
float64 qw # 四元数w分量
float64 qx # 四元数x分量
float64 qy # 四元数y分量
float64 qz # 四元数z分量

---

# Response part
bool success      # 规划是否成功
string message    # 返回的结果信息